/*
    id: the id of the card
    name: the name of the card
    cardimg: the display image for the card
    visualeffect: the visual affect that is made when the card is played
    attack: how much damage the card does
    defense: the health points of the card before the card is destroyed
    cost: how much mana the card costs
    abilityName: the name of the ability of the card
    ability: the generic typing of an ability
    abilityDescription: the special ability a card has if it has one
    abilityNumber: the ID of the given ability
        ability number may be useless if everyone has a unique ability and there aren't many repeats
    type: the type of the card, creature or spell.
    author: who created the card

 {
        id:0,
        name:"temp",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"temp",
    },
 */
//Add in a configuration with the deck that You can have at least 3 TA type cards in your deck (maximum of 3)
//This will allow us to fluff up the deck numberes without being a little extreme on anything else

const cardData=[{
    id:0,
    name:"Kris Jordan",
    cardimg: "link here",
    visualeffect:"link here",
    attack:3,
    defense:15,
    cost:10,
    abilityName:"First Year Hope",
    abilityDescription:"",
    ability:"Heal All allies including yourself",
    abilityNumber:0,
    type:"legendary",
    author:"Molly",
     },
    {
        id:1,
        name:"KMP",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityDescription:"",
        abilityName:"Reflect",
        abilityNumber:1,
        type:"temp",
        author:"Molly",
    },
    {
        id:2,
        name:"David Plaisted",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:3,
        name:"COMP110 TA",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:4,
        name:"Office Hours",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:5,
        name:"Curve",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:6,
        name:"Stack Overflow",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:7,
        name:"Exam",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Billy",
    },
    {
        id:8,
        name:"Professor Snoeyink",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:9,
        name:"Anish, the Prankster",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:10,
        name:"Comp Sci Overcrowding!",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:11,
        name:"Sitterson Pizza Event",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:12,
        name:"Legendary TA Rosh",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:13,
        name:"Robotics Lord Ron Alterovitz",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"This is a robotics professor here~~~~~",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:14,
        name:"Legendary Professor Bishop: Destroyer of Worlds",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:15,
        name:"WeedOut Classes",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:16,
        name:"BS to BA",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:17,
        name:"Caffeine Addiction",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:18,
        name:"Mips Rush",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Billy",
    },
    {
        id:19,
        name:"Sitterson: Home",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:20,
        name:"Procrastinate",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:21,
        name:"Coding Passion",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"Enjoying What You're Coding",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:21,
        name:"Djisktras Algorithm",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"Wait, We use Math?",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        //Talk to someone who has taken a class with Montek
        id:22,
        name:"Legendary Professor: Montek",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:23,
        name:"Legendary Professor: McMillan the Villain",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"Bioalgorithm Mastery",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:24,
        name:"Echoes of the Past: Pozefsky",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"temp",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:25,
        name:"Genome 100",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"Every Semester",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:26,
        name:"Internship",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        id:27,
        name:"BA to BS",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"",
        abilityDescription:"Lose 5 Health, Draw 2",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        //
        id:28,
        name:"BS to BA",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"",
        abilityDescription:"Discard 2 cards, gain 5 health.",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        //Higher health, lower attack monster
        id:29,
        name:"Computer Science Friends",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
    {
        //Higher attack, lower health monster
        id: 30,
        name:"Computer Science Enemies",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"",
        abilityDescription:"",
        abilityNumber:0,
        type:"temp",
        author:"Alan",
    },
];