/*
    id: the id of the card
    name: the name of the card
    cardimg: the display image for the card
    visualeffect: the visual affect that is made when the card is played
    attack: how much damage the card does
    defense: the health points of the card before the card is destroyed
    cost: how much mana the card costs
    abilityName: the name of the ability of the card
    ability: the special ability a card has if it has one
    abilityNumber: the ID of the given ability
        ability number may be useless if everyone has a unique ability and there aren't many repeats
    type: the type of the card, creature or spell.
    author: who created the card

 {
        id:0,
        name:"temp",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"temp",
    },
 */


const cardData=[{
    id:0,
    name:"Kris Jordan",
    cardimg: "link here",
    visualeffect:"link here",
    attack:3,
    defense:15,
    cost:10,
    abilityName:"First Year Hope",
    ability:"Heal All allies including yourself",
    abilityNumber:0,
    type:"legendary",
    author:"Molly",
     },
    {
        id:1,
        name:"KMP",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"",
        abilityName:"Reflect",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:2,
        name:"David Plaisted",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:2,
        name:"David Plaisted",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:3,
        name:"COMP110 TA",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:4,
        name:"Office Hours",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:5,
        name:"Curve",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:6,
        name:"Stack Overflow",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Molly",
    },
    {
        id:7,
        name:"Exam",
        cardimg: "link here",
        visualeffect:"link here",
        attack:0,
        defense:0,
        cost:0,
        ability:"temp",
        abilityName:"temp",
        abilityNumber:0,
        type:"temp",
        author:"Billy",
    },
];